config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#main"
  resources 'games' 
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
GUESSES_TO_IMAGE_MAPPING = {
    "6" => "Stage0.png",
    "5" => "Stage1.png",
    "4" => "Stage2.png",
    "3"=> "Stage3.png",
    "2" => "Stage4.png",
    "1"  => "Stage5.png",
    "0" => "Stage6.png"


}

class Game < ApplicationRecord
    def self.draw_board(remaining_num_guesses)
        image = GUESSES_TO_IMAGE_MAPPING[remaining_num_guesses.to_s]
        if !image 
        return "Stage7.png"
        end
        return image
    end
end

app/models/word.rb
class Word < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
require 'pry-rails'
class GamesController < ApplicationController

    def new 
    end

    def create 
        selected_word =  params["game"]["word"]
        if selected_word
            num_chars = selected_word.length
            inital_board_layout = "_ " * num_chars
            game = Game.create(name: selected_word, remaining_num_guesses: 6, guessed_letters: inital_board_layout )
        redirect_to :new_game, notice: "Game created with word #{selected_word}!. sharablelink: http://localhost:3000/games/#{game.id}"
        end
    end


    def show 
       game_id = params[:id] 
       @game = Game.find(game_id)
       @current_image = Game.draw_board(@game.remaining_num_guesses)
        @board_layout = @game.guessed_letters
        
    end

    def update 
        current_game = Game.find(params["id"].to_i)
        guessed_letter = params["game"]["name"].strip
        if current_game.remaining_num_guesses <= -1
            redirect_to current_game, notice: "Youve maxed out your guesses!"
            return
        end

        if current_game && !guessed_letter.blank?
           
           if current_game.name.include?(guessed_letter)
            updated_guessed_letters = current_game.guessed_letters.split(" ")
            current_game.name.each_char.with_index do |c,i|
                if c == guessed_letter
                    updated_guessed_letters[i] = c
                end
            end
            updated_game = Game.update(current_game.id, guessed_letters: updated_guessed_letters.join(" "))
 
            if current_game.name === updated_game.guessed_letters.split(" ").join("")
                redirect_to current_game, notice: "Letter: #{guessed_letter} was correct! Congrats you guessed the word!"
            else   
                redirect_to current_game, notice: "Letter: #{guessed_letter} was correct!"
            end

        else
            Game.update(current_game.id, remaining_num_guesses: current_game.remaining_num_guesses - 1)
            if current_game.remaining_num_guesses - 1 == -1 
                redirect_to current_game, notice: "Letter: #{guessed_letter} was incorrect! you lose. The word was #{current_game.name}" 
            else
                redirect_to current_game, notice: "Letter: #{guessed_letter} was incorrect!"
            end
            
           end
        end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def main 
        #@words = Word.all.map(&:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/games/new.html.erb
<% flash.each do |type, msg| %>
    <div>
      <%= msg %>
    </div>
  <% end %>



<%= form_tag(games_path, :method => "post") do %>
    <%= text_field(:game, :word) %>
    <%= submit_tag("Create Game") %>
  <% end %>

app/views/games/show.html.erb
<%= image_tag("#{@current_image}") %>

<%= @board_layout%>

<%= form_tag("/games/#{@game.id}", :method => "put") do %>
    <%= text_field(:game, :name, value: " ") %>
    <%= submit_tag("Guess Letter") %>
  <% end %>

  <% flash.each do |type, msg| %>
    <div>
      <%= msg %>
    </div>
  <% end %>

app/views/home/main.html.erb
Welcome to Hangman

<%= button_to  "Start a game", new_game_path, method: "get" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hangman</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
   
  </head>

  <body>
    <%= yield %>
  </body>
</html>